backend:
  name: github
  branch: master
  repo: radioarcane/radio-arcane.com

publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

site_url: https://radioarcane.netlify.com
display_url: https://radioarcane.netlify.com

collections:
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "_posts/events"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "event"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
      - label: "End DateTime"
        name: "start_datetime"
        widget: "datetime"
        required: false
        format: "YYYY-MM-DD HH:mm:ss"
        default: ""
      - label: "End DateTime"
        name: "end_datetime"
        widget: "datetime"
        required: false
        format: "YYYY-MM-DD HH:mm:ss"
        default: ""
      - label: "Image JPG (approx 800x800)"
        name: "image_jpg_2x"
        widget: "image"
        required: false
        default: ""
      - label: "Image JPG (approx 400x400)"
        name: "image_jpg"
        widget: "image"
        required: false
        default: ""
      - label: "Image WEBP (approx 800x800)"
        name: "image_webp_2x"
        widget: "image"
        required: false
        default: ""
      - label: "Image WEBP (approx 400x400)"
        name: "image_webp"
        widget: "image"
        required: false
        default: ""
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: false
        default: ""
      - label: "Short Description"
        name: "short_description"
        widget: "string"
        required: false
        default: ""
      - label: "Location"
        name: "location"
        widget: "object"
        required: false
        default: {}
        fields:
          - label: "Venue"
            name: "venue"
            widget: "string"
            default: "Art Sanctuary"
            required: false
          - label: "Venue Link"
            name: "venue_link"
            widget: "string"
            default: "https://www.facebook.com/pages/category/Arts---Entertainment/Art-Sanctuary-122260903695/"
            required: false
          - label: "Street Address"
            name: "address"
            widget: "string"
            default: "1433 S Shelby St."
            required: false
          - label: "Street Address 2"
            name: "address_2"
            widget: "string"
            required: false
          - label: "City"
            name: "city"
            widget: "string"
            default: "Louisville"
            required: false
          - label: "State"
            name: "state"
            widget: "string"
            default: "Kentucky"
            required: false
          - label: "Zipcode"
            name: "zipcode"
            widget: "string"
            default: "40217"
            required: false
          - label: "Google Map Link"
            name: "google_map_link"
            widget: "string"
            default: "https://www.google.com/maps/place/Art+Sanctuary/@38.2264103,-85.7413458,15z/data=!4m2!3m1!1s0x0:0xe8b5fa85d9ebd15f?ved=2ahUKEwjD0efWu_rfAhVKhq0KHV-nAdMQ_BIwDnoECAEQCA"
            required: false
      - label: "Facebook Event Link"
        name: "facebook_event_link"
        widget: "string"
        required: false
        default: ""
      - label: "Tickets Link"
        name: "tickets_link"
        widget: "string"
        required: false
        default: ""
  - name: "podcasts"
    label: "Podcasts"
    label_singular: "Podcast"
    folder: "_posts/podcasts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "podcast"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
        default: ""
        required: false
      - label: "Description"
        name: "description"
        default: ""
        widget: "markdown"
        required: false
      - label: "Mixcloud Link"
        name: "mixcloud_link"
        widget: "string"
        required: false
  - name: "playlists"
    label: "Playlists"
    label_singular: "Playlist"
    folder: "_posts/playlist"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "playlist"
      - label: "Playlist Type"
        name: "type"
        widget: "select"
        options: ["radio-arcane", "podcast", "arcane-alive"]
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Related Event"
        name: "event"
        widget: "relation"
        collection: "events"
        searchFields: ["title", "date"]
        valueField: "date"
        displayFields: ["title", "date"]
        required: false
        default: ""
        hint: "Select event or podcast below..."
      - label: "...Or Related Podcast"
        name: "podcast"
        widget: "relation"
        collection: "podcasts"
        searchFields: ["title", "date"]
        valueField: "date"
        displayFields: ["title", "date"]
        required: false
        default: ""
      - label: "Playlist"
        name: "playlist"
        widget: "list"
        required: true
        types:
          - label: "DJ Set"
            name: "dj_set"
            widget: "object"
            fields:
                - label: "DJ"
                  name: "dj"
                  widget: "select"
                  options: ["", "AndrOspore", "Brian Drabant", "Count Grozny", "Kaleidoscope", "Motuvius Rex", "Osiris Ani", "Sorrow-Vomit", "Talamasca", "Thulsa Goon"]
                  required: false
                  default: ""
                - label: "Guest DJ"
                  name: "guest_dj"
                  widget: "string"
                  required: false
                  default: ""
                - label: "Tracks"
                  name: "tracks"
                  widget: "list"
                  default: []
                  types:
                    - label: "Track"
                      name: "track"
                      widget: "object"
                      required: true
                      fields:
                        - label: "Artist"
                          name: "artist"
                          widget: "string"
                          required: true
                        - label: "Song"
                          name: "song"
                          widget: "string"
                          required: true
                        - label: "Request"
                          name: "request"
                          widget: "select"
                          options:
                            - { label: "No", value: "no"}
                            - { label: "Artist", value: "artist"}
                            - { label: "Song", value: "song"}
                          default: "no"
                          required: false
                        - label: "Artist Links"
                          name: "artist_links"
                          widget: "relation"
                          collection: "artist_links"
                          searchFields: ["title"]
                          valueField: "title"
                          displayFields: ["title"]
                          required: false
                          default: ""
  - name: "artist_links"
    label: "Artist Links"
    label_singular: "Artist Link"
    folder: "_posts/artist-links"
    create: true
    slug: "{{slug}}"
    fields:
      - label: Artist
        name: "title"
        widget: "string"
        required: true
      - label: "Apple Music"
        name: "apple_music"
        widget: "string"
        required: false
        default: ""
      - label: "Bandcamp"
        name: "bandcamp"
        widget: "string"
        required: false
        default: ""
      - label: "Facebook"
        name: "facebook"
        widget: string
        required: false
        default: ""
      - label: "Google Music"
        name: "google_music"
        widget: "string"
        required: false
        default: ""
      - label: "Instagram"
        name: "instagram"
        widget: "string"
        required: false
        default: ""
      - label: "Soundcloud"
        name: "soundcloud"
        widget: "string"
        required: false
        default: ""
      - label: "Spotify"
        name: "spotify"
        widget: "string"
        required: false
        default: ""
      - label: "Twitter"
        name: "twitter"
        widget: "string"
        required: false
        default: ""
      - label: "Website"
        name: "website"
        widget: "string"
        required: false
        default: ""
      - label: "Youtube"
        name: "youtube"
        widget: "string"
        required: false
        default: ""
