backend:
  name: github
  branch: master
  repo: radioarcane/radio-arcane.com

publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

site_url: https://radioarcane.netlify.com
display_url: https://radioarcane.netlify.com

collections:
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "_posts/events"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "event"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
      - label: "End DateTime"
        name: "start_datetime"
        widget: "datetime"
        required: false
      - label: "End DateTime"
        name: "end_datetime"
        widget: "datetime"
        required: false
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: false
      - label: "Short Description"
        name: "short_description"
        widget: "string"
        required: false
      - label: "Location"
        name: "location"
        widget: "object"
        required: false
        fields:
          - label: "Venue"
            name: "venue"
            widget: "string"
            default: "Art Sanctuary"
            required: false
          - label: "Venue Link"
            name: "venue_link"
            widget: "string"
            default: "https://www.facebook.com/pages/category/Arts---Entertainment/Art-Sanctuary-122260903695/"
            required: false
          - label: "Street Address"
            name: "address"
            widget: "string"
            default: "1433 S Shelby St."
            required: false
          - label: "Street Address 2"
            name: "address_2"
            widget: "string"
            required: false
          - label: "City"
            name: "city"
            widget: "string"
            default: "Louisville"
            required: false
          - label: "State"
            name: "state"
            widget: "string"
            default: "Kentucky"
            required: false
          - label: "Zipcode"
            name: "zipcode"
            widget: "string"
            default: "40217"
            required: false
          - label: "Google Map Link"
            name: "google_map_link"
            widget: "string"
            default: "https://www.google.com/maps/place/Art+Sanctuary/@38.2264103,-85.7413458,15z/data=!4m2!3m1!1s0x0:0xe8b5fa85d9ebd15f?ved=2ahUKEwjD0efWu_rfAhVKhq0KHV-nAdMQ_BIwDnoECAEQCA"
            required: false
      - label: "Facebook Event Link"
        name: "facebook_event_link"
        widget: "string"
        required: false
      - label: "Tickets Link"
        name: "tickets_link"
        widget: "string"
        required: false
  - name: "podcasts"
    label: "Podcasts"
    label_singular: "Podcast"
    folder: "_posts/podcasts"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "podcast"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
        required: false
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: false
      - label: "Mixcloud Link"
        name: "mixcloud_link"
        widget: "string"
        required: false
      - label: "Soundcloud Link"
        name: "soundcloud_link"
        widget: "string"
        required: false
  - name: "playlists"
    label: "Playlists"
    label_singular: "Playlist"
    folder: "_posts/playlist"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "playlist"
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["radio-arcane", "podcast", "arcane-alive"]
      - label: "Title"
        name: "title"
        widget: "String"
      - label: "Related Event"
        name: "event"
        widget: "relation"
        collection: "events"
        searchFields: ["title", "date"]
        valueField: "date"
        displayFields: ["title", "date"]
        required: false
      - label: "Related Podcast"
        name: "podcast"
        widget: "relation"
        collection: "podcasts"
        searchFields: ["title", "date"]
        valueField: "date"
        displayFields: ["title", "date"]
        required: false
      - label: "Playlist"
        name: "playlist"
        widget: "list"
        required: false
        fields:
          - label: "Set"
            name: "set"
            widget: "list"
            required: false
            fields:
              - label: "DJ"
                name: "dj"
                widget: "object"
                required: false
                fields:
                  - label: "Name"
                    name: "Name"
                    widget: "select"
                    options: [AndrOspore", "Brian Drabant", "Count Grozny", "Kaleidoscope", "Motuvius Rex", "Osiris Ani", "Sorrow-Vomit", "Talamasca", "Thulsa Goon"]
                  - label: "Guest DJ"
                    name: "guest_dj"
                    widget: "string"
              - label: "Tracks"
                name: "tracks"
                widget: "list"
                required: false
                field:
                  - label: "Track"
                    name: "track"
                    fields:
                      - label: "Artist"
                        name: "artist"
                        widget: "string"
                      - label: "Song"
                        name: "song"
                        widget: "string"
                      - label: "Request for Artist"
                        name: "request_artist"
                        widget: "boolean"
                      - label: "Request for Song"
                        name: "request_song"
                        widget: "boolean"
                      - label: "Links"
                        name: "links"
                        widget: "options"
                        required: false
                        fields:
                          - label: "Apple Music"
                            name: "apple_music"
                            widget: "string"
                          - label: "Bandcamp"
                            name: "bandcamp"
                            widget: "string"
                          - label: "Facebook"
                            name: "facebook"
                            widget: string
                          - label: "Google Music"
                            name: "google_music"
                            widget: "string"
                          - label: "Instagram"
                            name: "instagram"
                            widget: "string"
                          - label: "Soundcloud"
                            name: "soundcloud"
                            widget: "string"
                          - label: "Spotify"
                            name: "spotify"
                            widget: "string"
                          - label: "Twitter"
                            name: "twitter"
                            widget: "string"
                          - label: "Website"
                            name: "website"
                            widget: "string"
                          - label: "Youtube"
                            name: "youtube"
                            widget: "string"
          - label: "Performance By"
            name: "performer"
            widget: "string"
            required: false
          - label: "Links"
            name: "links"
            widget: "options"
            required: false
            fields:
              - label: "Apple Music"
                name: "apple_music"
                widget: "string"
              - label: "Bandcamp"
                name: "bandcamp"
                widget: "string"
              - label: "Facebook"
                name: "facebook"
                widget: string
              - label: "Google Music"
                name: "google_music"
                widget: "string"
              - label: "Instagram"
                name: "instagram"
                widget: "string"
              - label: "Soundcloud"
                name: "soundcloud"
                widget: "string"
              - label: "Spotify"
                name: "spotify"
                widget: "string"
              - label: "Twitter"
                name: "twitter"
                widget: "string"
              - label: "Website"
                name: "website"
                widget: "string"
              - label: "Youtube"
                name: "youtube"
                widget: "string"
