backend:
  name: github
  branch: master
  repo: radioarcane/radio-arcane.com

publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

site_url: https://radioarcane.netlify.com
display_url: https://radioarcane.netlify.com

collections:
  - name: "locations"
    label: "Locations"
    label_singular: "Location"
    folder: "_posts/locations"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Venue"
        name: "title"
        widget: "string"
        default: ""
        required: true
      - label: "ID"
        name: "id"
        widget: "string"
        required: true
        hint: "Unique name, all lowercase, no spaces preferred"
      - label: "Venue Link"
        name: "venue_link"
        widget: "string"
        default: ""
        required: false
      - label: "Street Address"
        name: "address"
        widget: "string"
        default: ""
        required: false
      - label: "Street Address 2"
        name: "address_2"
        widget: "string"
        required: false
        default: ""
      - label: "City"
        name: "city"
        widget: "string"
        default: ""
        required: false
      - label: "State"
        name: "state"
        widget: "string"
        default: ""
        required: false
      - label: "Zipcode"
        name: "zipcode"
        widget: "string"
        default: ""
        required: false
      - label: "Google Map Link"
        name: "google_map_link"
        widget: "string"
        default: ""
        required: false
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "_posts/events"
    create: true
    slug: "{{fields.event_type}}-{{fields.date}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "event"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
        required: true
      - label: "Start DateTime"
        name: "start_datetime"
        widget: "datetime"
        required: false
        format: "YYYY-MM-DD HH:mm:ss"
        default: ""
      - label: "End DateTime"
        name: "end_datetime"
        widget: "datetime"
        required: false
        format: "YYYY-MM-DD HH:mm:ss"
        default: ""
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
        default: ""
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: false
        default: ""
      - label: "Short Description"
        name: "short_description"
        widget: "string"
        required: false
        default: ""
      - label: "Location"
        name: "location"
        widget: "relation"
        collection: "locations"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: true
        default: ""
      - label: "Facebook Event Link"
        name: "facebook_event_link"
        widget: "string"
        required: false
        default: ""
      - label: "Tickets Link"
        name: "tickets_link"
        widget: "string"
        required: false
        default: ""
      - label: "Playlist"
        name: "playlist"
        widget: "relation"
        collection: "playlists"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: false
        default: ""
  - name: "podcasts"
    label: "Podcasts"
    label_singular: "Podcast"
    folder: "_posts/podcasts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "podcast"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
        default: ""
        required: true
      - label: "Description"
        name: "description"
        default: ""
        widget: "markdown"
        required: false
      - label: "Mixcloud Link"
        name: "mixcloud_link"
        widget: "string"
        required: false
        default: ""
      - label: "Soundcloud Link"
        name: "soundcloud_link"
        widget: "string"
        required: false
        default: ""
      - label: "Playlist"
        name: "playlist"
        widget: "relation"
        collection: "playlists"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: false
        default: ""
  - name: "playlists"
    label: "Playlists"
    label_singular: "Playlist"
    folder: "_posts/playlists"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "playlist"
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Playlist Type"
        name: "type"
        widget: "select"
        options: ["radio-arcane", "podcast", "arcane-alive"]
      - label: "Playlist"
        name: "playlist"
        widget: "list"
        required: true
        types:
          - label: "DJ Set"
            name: "dj_set"
            widget: "object"
            fields:
                - label: "DJ"
                  name: "dj"
                  widget: "select"
                  options: ["", "AndrOspore", "Brian Drabant", "Count Grozny", "Kaleidoscope", "Motuvius Rex", "Osiris Ani", "Sorrow-Vomit", "Talamasca", "Thulsa Goon"]
                  required: false
                  default: ""
                - label: "Guest DJ"
                  name: "guest_dj"
                  widget: "string"
                  required: false
                  default: ""
                - label: "Tracks"
                  name: "tracks"
                  widget: "list"
                  default: []
                  types:
                    - label: "Track"
                      name: "track"
                      widget: "object"
                      required: true
                      fields:
                        - label: "Artist"
                          name: "artist"
                          widget: "string"
                          required: true
                        - label: "Song"
                          name: "song"
                          widget: "string"
                          required: true
                        - label: "Request"
                          name: "request"
                          widget: "select"
                          options:
                            - { label: "No", value: "no"}
                            - { label: "Artist", value: "artist"}
                            - { label: "Song", value: "song"}
                          default: "no"
                          required: false
                        - label: "Artist Links"
                          name: "artist_links"
                          widget: "relation"
                          collection: "artist_links"
                          searchFields: ["title"]
                          valueField: "id"
                          displayFields: ["title"]
                          required: false
                          default: ""
  - name: "artist_links"
    label: "Artist Links"
    label_singular: "Artist Link"
    folder: "_posts/artist-links"
    create: true
    slug: "{{slug}}"
    fields:
      - label: Artist
        name: "title"
        widget: "string"
        required: true
      - label: ID
        name: "id"
        widget: "string"
        required: true
      - label: "Apple Music"
        name: "apple_music"
        widget: "string"
        required: false
        default: ""
      - label: "Bandcamp"
        name: "bandcamp"
        widget: "string"
        required: false
        default: ""
      - label: "Facebook"
        name: "facebook"
        widget: string
        required: false
        default: ""
      - label: "Google Music"
        name: "google_music"
        widget: "string"
        required: false
        default: ""
      - label: "Instagram"
        name: "instagram"
        widget: "string"
        required: false
        default: ""
      - label: "Soundcloud"
        name: "soundcloud"
        widget: "string"
        required: false
        default: ""
      - label: "Spotify"
        name: "spotify"
        widget: "string"
        required: false
        default: ""
      - label: "Twitter"
        name: "twitter"
        widget: "string"
        required: false
        default: ""
      - label: "Website"
        name: "website"
        widget: "string"
        required: false
        default: ""
      - label: "Youtube"
        name: "youtube"
        widget: "string"
        required: false
        default: ""
