backend:
  name: github
  branch: master
  repo: radioarcane/radio-arcane.com

media_folder: "/static/img/uploads"
public_folder: "/img/uploads"

site_url: https://radioarcane.netlify.com
display_url: https://radioarcane.netlify.com

collections:
  - name: "locations"
    label: "Locations"
    label_singular: "Location"
    folder: "_posts/locations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Venue", name: "title", widget: "string"}
      - {label: "Venue Link", name: "venue_link", widget: "string", required: false, default: ""}
      - {label: "Street Address", name: "address", widget: "string"}
      - {label: "Street Address", name: "address_2", widget: "string", required: false, default: ""}
      - {label: "City", name: "city", widget: "string"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "Zipcode", name: "zipcode", widget: "string"}
      - {label: "Google Map Link", name: "google_map_link", widget: "string", required: false, default: ""}
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "_posts/events"
    create: true
    slug: "{{fields.event_type}}-{{fields.date}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display Name", name: "display_name", widget: "string"}
      - {label: "Event Type", name: "event_type", widget: "select", options: [radio-arcane", "arcane-alive"]}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Start DateTime", name: "start_datetime", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: false, default: ""}
      - {label: "End DateTime", name: "end_datetime", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: false, default: ""}
      - {label: "Image", name: "image", widget: "image", required: false, default: ""}
      - {label: "Description", name: "description", widget: "markdown", required: false, default: ""}
      - {label: "Short Description", name: "short_description", widget: "string", required: false, default: ""}
      - {label: "Location", name: "location", widget: "relation", collection: "locations", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false, default: ""}
      - {label: "Facebook Event Link", name: "facebook_event_link", widget: "string", required: false, default: ""}
      - {label: "Tickets Link", name: "tickets_link", widget: "string", required: false, default: ""}
      - {label: "Playlist", name: "playlist", widget: "relation", required: false, default: "", collection: "playlists", searchFields: ["title", "date", "display_name"], valueField: "title", displayFields: ["title"]}
  - name: "podcasts"
    label: "Podcasts"
    label_singular: "Podcast"
    folder: "_posts/podcasts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "podcast"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display Name", name: "display_name", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Description", name: "description", widget: "markdown", required: false, default: ""}
      - {label: "Short Description", name: "short_description", widget: "string", required: false, default: ""}
      - {label: "Mixcloud Link", name: "mixcloud_link", widget: "string", required: false, default: ""}
      - {label: "Soundcloud Link", name: "soundcloud_link", widget: "string", required: false, default: ""}
      - {label: "Playlist", name: "playlist", widget: "relation", required: false, default: "", collection: "playlists", searchFields: ["title", "date", "display_name"], valueField: "title", displayFields: ["title"]}
  - name: "playlists"
    label: "Playlists"
    label_singular: "Playlist"
    folder: "_posts/playlists"
    create: true
    slug: "{{fields.playlist_type}}-{{fields.date}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "playlist"}
      - {label: "Title", name: "title", widget: "string"}
      - {Label: "Playlist Type", name: "playlist_type", widget: "select", options: ["radio-arcane", "podcast", "arcane-alive"]}
      - {Label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - label: "Sets"
        name: "sets"
        widget: "list"
        required: true
        default: []
        types:
          - label: "DJ Set"
            name: "dj_set"
            widget: "object"
            required: false
            default: {"dj": "", "guest_dj": ""}
            fields:
              - {label: "DJ", name: "dj", widget: "select", options: ["", "AndrOspore", "Brian Drabant", "Count Grozny", "Kaleidoscope", "Motuvius Rex", "Osiris Ani", "Sorrow-Vomit", "Talamasca", "Thulsa Goon"], required: false, default: ""}
              - {label: "Guest DJ", name: "guest_dj", widget: "string", required: false, default: ""}
              - label: "Tracks"
                name: "tracks"
                widget: "list"
                required: true
                default: []
                fields:
                  - {label: "Artist", name: "Artist", widget: "string"}
                  - {label: "Song", name: "song", widget: "string"}
                  - label: "Request"
                    name: "request"
                    widget: "select"
                    options:
                      - { label: "No", value: "no"}
                      - { label: "Artist Request", value: "artist"}
                      - { label: "Song Request", value: "song"}
                    required: false
          - label: "Performance"
            name: "performance"
            widget: "object"
            required: false
            default: {"performer": ""}
            fields:
              - {label: "Performer", name: "performer", widget: "string"}
  - name: "artist_links"
    label: "Artist Links"
    label_singular: "Artist Link"
    folder: "_posts/artist-links"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Artist", name: "title", widget: "string"}
      - {label: "Apple Music", name: "apple_music", widget: "string", required: false, default: ""}
      - {label: "Bandcamp", name: "bandcamp", widget: "string", required: false, default: ""}
      - {label: "Facebook", name: "facebook", widget: "string", required: false, default: ""}
      - {label: "Google Music", name: "google_music", widget: "string", required: false, default: ""}
      - {label: "Instagram", name: "instagram", widget: "string", required: false, default: ""}
      - {label: "Soundcloud", name: "soundcloud", widget: "string", required: false, default: ""}
      - {label: "Spotify", name: "spotify", widget: "string", required: false, default: ""}
      - {label: "Twitter", name: "twitter", widget: "string", required: false, default: ""}
      - {label: "Website", name: "website", widget: "string", required: false, default: ""}
      - {label: "Youtube", name: "youtube", widget: "string", required: false, default: ""}
