backend:
  name: github
  branch: master
  repo: radioarcane/radio-arcane.com

media_folder: "/static/img/uploads"
public_folder: "/img/uploads"

site_url: https://www.radio-arcane.com
display_url: https://www.radio-arcane.com

publish_mode: editorial_workflow

collections:
  - name: "locations"
    label: "Locations"
    label_singular: "Location"
    folder: "_posts/locations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Venue", name: "title", widget: "string"}
      - {label: "Venue Link", name: "venueLink", widget: "string", required: false, default: ""}
      - {label: "Street Address", name: "address", widget: "string"}
      - {label: "Street Address", name: "address2", widget: "string", required: false, default: ""}
      - {label: "City", name: "city", widget: "string"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "Zipcode", name: "zipcode", widget: "string"}
      - {label: "Google Map Link", name: "googleMapLink", widget: "string", required: false, default: ""}
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "_posts/events"
    create: true
    slug: "{{fields.eventtype}}-{{fields.date}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display Name", name: "displayName", widget: "string"}
      - {label: "Event Type", name: "eventType", widget: "select", options: ["radio-arcane", "arcane-alive", "warped-wednesday","convergence"]}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Start DateTime", name: "startDatetime", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: false, default: ""}
      - {label: "End DateTime", name: "endDatetime", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: false, default: ""}
      - {label: "Image", name: "image", widget: "image", required: false, default: ""}
      - {label: "Description", name: "description", widget: "markdown", required: false, default: ""}
      - {label: "Short Description", name: "shortDescription", widget: "string", required: false, default: ""}
      - {label: "Location", name: "location", widget: "relation", collection: "locations", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false, default: ""}
      - {label: "Facebook Event Link", name: "facebookEventLink", widget: "string", required: false, default: ""}
      - {label: "Tickets Link", name: "ticketsLink", widget: "string", required: false, default: ""}
      - {label: "Cover Price", name: "cover", widget: "string", required: false, default: ""}
      - {label: "Playlist", name: "playlist", widget: "relation", required: false, default: "", collection: "playlists", searchFields: ["title", "date", "displayName"], valueField: "title", displayFields: ["title"]}
  - name: "podcasts"
    label: "Podcasts"
    label_singular: "Podcast"
    folder: "_posts/podcasts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "podcast"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false, default: ""}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Description", name: "description", widget: "markdown", required: false, default: ""}
      - {label: "Short Description", name: "shortDescription", widget: "string", required: false, default: ""}
      - {label: "Mixcloud Link", name: "mixcloudLink", widget: "string", required: false, default: ""}
      - {label: "Soundcloud Link", name: "soundcloudLink", widget: "string", required: false, default: ""}
      - {label: "Podbean Link", name: "podbeanLink", widget: "string", required: false, default: ""}
      - {label: "Spotify Link", name: "spotifyLink", widget: "string", required: false, default: ""}
      - {label: "Playlist", name: "playlist", widget: "relation", required: false, default: "", collection: "playlists", searchFields: ["title", "date", "displayName"], valueField: "title", displayFields: ["title"]}
  - name: "playlists"
    label: "Playlists"
    label_singular: "Playlist"
    folder: "_posts/playlists"
    create: true
    slug: "{{fields.playlistType}}-{{fields.date}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "playlist"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display Title", name: "displayName", widget: "string"}
      - {Label: "Playlist Type", name: "playlistType", widget: "select", options: ["radio-arcane", "podcast", "arcane-alive"]}
      - {Label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - label: "Sets"
        name: "sets"
        widget: "list"
        required: true
        default: []
        types:
          - label: "DJ Set"
            name: "djSet"
            widget: "object"
            required: false
            default: {"dj": "", "guestDj": ""}
            fields:
              - {label: "DJ", name: "djName", widget: "select", options: ["", "AndrOspore", "Brian Cole", "Brian Drabant", "Count Grozny", "Kaleidoscope", "Motuvius Rex", "Osiris Ani", "Sorrow-Vomit", "Talamasca", "Thulsa Goon", "Talamasca & Thulsa Goon"], required: false, default: ""}
              - {label: "Guest DJ", name: "guestDj", widget: "string", required: false, default: ""}
              - label: "Tracks"
                name: "tracks"
                widget: "list"
                required: true
                default: []
                fields:
                  - {label: "Artist", name: "artist", widget: "string"}
                  - {label: "Song", name: "song", widget: "string"}
                  - label: "Request"
                    name: "request"
                    widget: "select"
                    options:
                      - { label: "No", value: "no"}
                      - { label: "Artist Request", value: "artist"}
                      - { label: "Song Request", value: "song"}
                    required: false
          - label: "Performance"
            name: "performance"
            widget: "object"
            required: false
            default: {"performer": ""}
            fields:
              - {label: "Performer", name: "performer", widget: "string"}
      - label: "Mixcloud Links"
        name: "mixcloudLinks"
        widget: "list"
        default: []
        field: {label: "URL", name: "url", widget: "string"}
  - name: "artistLinks"
    label: "Artist Links"
    label_singular: "Artist Link"
    folder: "_posts/artist-links"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Artist", name: "title", widget: "string"}
      - {label: "Apple Music", name: "appleMusic", widget: "string", required: false, default: ""}
      - {label: "Bandcamp", name: "bandcamp", widget: "string", required: false, default: ""}
      - {label: "Discogs", name: "discogs", widget: "string", required: false, default: ""}
      - {label: "Facebook", name: "facebook", widget: "string", required: false, default: ""}
      - {label: "Google Music", name: "googleMusic", widget: "string", required: false, default: ""}
      - {label: "Instagram", name: "instagram", widget: "string", required: false, default: ""}
      - {label: "Soundcloud", name: "soundcloud", widget: "string", required: false, default: ""}
      - {label: "Spotify", name: "spotify", widget: "string", required: false, default: ""}
      - {label: "Twitter", name: "twitter", widget: "string", required: false, default: ""}
      - {label: "Website", name: "website", widget: "string", required: false, default: ""}
      - {label: "Youtube", name: "youtube", widget: "string", required: false, default: ""}
